option(CMSIS_DSP_ENABLED "" on)
set(PROJECT_DEFS
    USE_RTT_PRINT
    LOG_LEVEL_DEBUG
    EVENT_POOL_SIZE=2
    THREADX # THREADX  NORTOS  FREERTOS
    CHIP_I2C_WRITE_IT_ENABLED=1
    CHIP_I2C_WRITE_DMA_ENABLED=0
    CHIP_I2C_READ_IT_ENABLED=1
    CHIP_I2C_READ_DMA_ENABLED=0
    CHIP_SPI_WRITE_IT_ENABLED=1
    CHIP_SPI_WRITE_DMA_ENABLED=0
    CHIP_SPI_READ_IT_ENABLED=1
    CHIP_SPI_READ_DMA_ENABLED=0
    CHIP_UART_WRITE_IT_ENABLED=1
    CHIP_UART_WRITE_DMA_ENABLED=0
    CHIP_UART_READ_IT_ENABLED=0
    CHIP_UART_READ_DMA_ENABLED=1
    COMMAND_SERVER_STACK_SIZE=2048
)